# Assign PR to Author
# https://github.com/samspills/assign-pr-to-author

name: Auto Assign PR

on:
  pull_request:
    types: [opened]

jobs:
  assignAuthor:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Assign PR
      uses: samspills/assign-pr-to-author@v1.0.1
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
